server:
  port: 9000

spring:
  application:
    name: demo-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

logging:
  file: ./logs/${spring.application.name}/log
