server:
  port: 9000

spring:
  application:
    name: demo-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  zipkin:
    #Download zipkin-server: https://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/
    #execute: java -jar zipkin-server-2.9.4-exec.jar
    base-url: http://localhost:9411

logging:
  file: ./logs/${spring.application.name}/log
