server:
  port: 8081
spring:
  application:
    name: user-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

